:PROPERTIES:
:ID:       650EFF9F-D56C-449F-A702-4BE75C0C090E
:END:
#+title: Essay - How to Make Your Bookmarks Valuable
#+filetags: :permanent

* Intro
Are we blessed or cursed?

In the past, people were fighting for resources. For knowledge workers, the resources was information. They fought for access to this information because having it gave them a higher probability of success. Now, people don't worry about access anymore. People start being overwhelmed by the amount of information they have to process.

I found people on the internet suggest many ways to overcome overwhelm when processing excessive information. One of them is bookmarking with their hacks. However, I don't see these suggestions as useful.
* Why bookmarks are not working?
Many of you have heard "Oh, you can save it to your bookmarks and see it later! Easy.".

Yet, have you ever looked at bookmarked you save? I never have. It only caused me to feel guilty. Typically, it seems I follow

1. I find a string of interesting articles or youtube videos.

2. I bookmark

3. Then, I'm supposed to go back and read through but.......

I decide to leave it there for now. And I feel overwhelemd by the amount of bookmarks. I start making excuses. "Oh, those are not important, actually".

Another problem is every app now offers in-house bookmark feature. It seems convenient at first glance as you don't have to leave the app. Yet, this makes information even scattered across apps. Have you been lost where you bookmarks you want to see now and frustrated?
* Two extreme hacks
You can easily find various hacks that people suggest. I will show you two extremes.

One side of this continuum is team "we save ALL". People in this side believe that they can process all bookmarks they save. So, they try to devise a system. One example is to create a separate bookmark folder for each category. Folder a for engineering, Folder b for book reviews, and Folder c for psychology, for exmaple. People even give different colors for folders and use extensions. The problem with this approach is in mindless collecting. You wish future yourself have enough time to process information you collected.

The other side is team "we don't use bookmarks at all". People in this side are aware that they will not come back to the saved bookmarks. Instead of accumulating debt of information, they open up any articles, videos and consume content right away. Essentially, debt free, right? The problem with this approach is in context switching. Whenever you find something interesting, you drop the current context. This can be a big load on your brain.

Why we still want to bookmark though?
Now, you see the extreme cases and may ask a question: "Why on earth do we still want to save bookmarks even with these headaches?" With the increased access to information, people seem to experience fear of missing out (FOMO) than ever. "What if I am the only one who doesn't know about it?" "What if this is very important piece of information in the unknown future?" These thoughts make us anxious and we collect information. This hit me hard last year. Through struggles and experiments, I was able to convert seemingly useless bookmarks to priceless elements for my craft with make a following system.
* First, apply higher stand for information
You want to collect the best pieces of information in bookmarks so you can grow your digital garden and produce meaningful and impactful works. Garbage in, garbage out is an axiom that is often used to emphasize the importance of input quality in the computing world. Yet, this can be also applied to your information consumption. We have a vast amount of information from the various sources - Twitter, Youtube, articles, or books. However, the quality of content is directly proportional to the time and effort spent creating it.

If you agree with this formula, you may find that long-form content can provide more fruitful ideas, insights, or motivations than shorter forms. This is because long-form content often requires more time and effort to create, which means that authors have invested more in producing high-quality content.

Even with the long form content, it's worth asking yourself, "Is this information truely valuable and relevant to my goals and interests?". If the answer is yes, then it may be worth saving. However, if the information is mildly interesting or not directly related to your needs, it may be better to simply move on and not clutter your bookmarks with unnecessary items. If each of your bookmarks is gem, isn't it exciting to open it up and convert into ingredients of your craft. Remember, Garbage in, garbage out.
* Second, centralize your bookmarks
As I mentioned, you can bookmark anywhere. You may have some in your web browser and some in your mobile apps. This imposes an overload on you when you have to organize them. The solution is to centralize your bookmarks when you are about to save them. How? Start your digital garden if you haven't yet. You need a central place to save all the elements so you can revisit and use them produce your work without worrying to lose them. I cannot emphasize the importance of digital garden much.

If you set up your digital garden, then give them a short description instead of putting only URLs. For example, You will understand better "it's about how to write well in the morning" with the URL than simply the URL itself when you visit later. This will save your effort a lot. You can also tag bookmarks if you use them. I'd put ":writing" tag in the above example that I can easily query.
* Conclusion
We are exposed to unprecedented amount of information in history and a lot of people are struggling to deal with it. This can be blessing if you manage well. Many people suggest hacks to deal with it. Unfortunately, hacks usually treat symptoms, ignoring the root cause. We need a system not to be swayed by information and manage it well. And I believe in being selective in choosing information and centralizing your information in your digital vault will be the key pillars to make a sustainable knowledge management system.
